import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Check, ShieldCheck, X } from 'lucide-react';
import { cn } from '@/utils/cn';
import { severityMeta } from '@/utils/severity';
/** Response-header audit grid with per-header remediation guidance. */
export function SecurityHeaders({ headers }) {
    const present = headers.filter((h) => h.present).length;
    const score = headers.length ? Math.round((present / headers.length) * 100) : 0;
    return (_jsxs("div", { className: "min-w-0", children: [_jsxs("div", { className: "mb-2 flex flex-wrap items-center gap-2", children: [_jsxs("span", { className: "inline-flex items-center gap-1.5 text-[11px] font-semibold tracking-[0.01em] text-ink-2", children: [_jsx(ShieldCheck, { className: "size-3.5 text-cyber", "aria-hidden": true }), " Header coverage"] }), _jsxs("span", { className: cn('mono tnum text-[13px] font-bold', score >= 80 ? 'text-term' : score >= 50 ? 'text-medium' : 'text-critical'), children: [score, "%"] }), _jsxs("span", { className: "mono text-[11px] text-ink-4", children: [present, "/", headers.length, " PRESENT"] }), _jsx("span", { className: "flex-1" }), _jsx("div", { className: "h-1.5 w-28 overflow-hidden rounded-[1px] bg-raised", children: _jsx("div", { className: cn('h-full', score >= 80 ? 'bg-term' : score >= 50 ? 'bg-medium' : 'bg-critical'), style: { width: `${score}%` }, "aria-hidden": true }) })] }), _jsx("ul", { className: "space-y-px", children: headers.map((header) => {
                    const meta = severityMeta(header.severity);
                    return (_jsxs("li", { className: "rounded-[2px] border border-transparent px-2 py-1.5 transition-colors hover:border-line hover:bg-base", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: cn('flex size-4 shrink-0 items-center justify-center rounded-[2px] border', header.present ? 'border-term/35 bg-term/10 text-term' : cn(meta.border, meta.soft, meta.text)), "aria-hidden": true, children: header.present ? _jsx(Check, { className: "size-2.5" }) : _jsx(X, { className: "size-2.5" }) }), _jsx("span", { className: "mono min-w-0 flex-1 truncate text-[11px] text-ink", children: header.name }), header.present ? (_jsx("span", { className: "mono shrink-0 text-[11px] font-bold tracking-[0.01em] text-term uppercase", children: "PRESENT" })) : (_jsxs("span", { className: cn('mono shrink-0 text-[11px] font-bold tracking-[0.01em] uppercase', meta.text), children: [meta.glyph, " MISSING"] }))] }), header.value ? (_jsx("p", { className: "mono mt-1 truncate pl-6 text-[11px] text-cyber", title: header.value, children: header.value })) : null, !header.present ? (_jsxs("p", { className: "mono mt-1 pl-6 text-[11px] leading-relaxed text-ink-4", children: ["\u2192 ", header.recommendation] })) : null] }, header.name));
                }) })] }));
}
