import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useLocation } from 'react-router-dom';
import { ArrowLeft, Compass, Terminal } from 'lucide-react';
import { Panel } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { NAVIGATION } from '@/app/router/navigation';
import { TerminalBlock } from '@/components/ui/Terminal';
/** 404 — terminal-flavoured dead end with real routes to recover from. */
export default function NotFound() {
    const { pathname } = useLocation();
    const links = NAVIGATION.flatMap((group) => group.items);
    return (_jsxs("div", { className: "mx-auto w-full max-w-3xl space-y-2.5 p-3 sm:p-6", children: [_jsxs(Panel, { className: "min-w-0", accent: "critical", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx("span", { className: "mono flex size-10 shrink-0 items-center justify-center rounded-[2px] border border-critical/40 bg-critical/10 text-[13px] font-bold text-critical", children: "404" }), _jsxs("div", { className: "min-w-0", children: [_jsx("h1", { className: "text-[16px] font-semibold text-ink", children: "Route not found" }), _jsxs("p", { className: "mono mt-1 text-[11.5px] leading-relaxed break-all text-ink-3", children: ["No view is registered at ", _jsx("span", { className: "text-critical", children: pathname }), "."] })] })] }), _jsx("div", { className: "mt-3", children: _jsxs(TerminalBlock, { title: "ROUTER", maxHeight: 132, children: [_jsxs("div", { className: "text-ink-3", children: ["> resolve --path ", pathname] }), _jsx("div", { className: "text-critical", children: "[\u2717] no route matches this path" }), _jsx("div", { className: "text-ink-4", children: "[i] checking the navigation manifest\u2026" }), _jsxs("div", { className: "text-term", children: ["[\u2713] ", links.length, " registered routes available"] })] }) }), _jsxs("div", { className: "mt-3 flex flex-wrap gap-1.5", children: [_jsx(Link, { to: "/dashboard", children: _jsx(Button, { variant: "primary", size: "sm", icon: _jsx(ArrowLeft, { className: "size-3.5", "aria-hidden": true }), children: "Return to dashboard" }) }), _jsx(Link, { to: "/incidents", children: _jsx(Button, { variant: "secondary", size: "sm", icon: _jsx(Compass, { className: "size-3.5", "aria-hidden": true }), children: "Incident queue" }) })] })] }), _jsxs(Panel, { title: "Available Routes", icon: _jsx(Terminal, { className: "size-3.5", "aria-hidden": true }), className: "min-w-0", children: [_jsx("ul", { className: "grid gap-1.5 sm:grid-cols-2", children: links.map((link) => (_jsx("li", { children: _jsxs(Link, { to: link.to, className: "group flex items-center gap-2 rounded-[2px] border border-line bg-base px-2 py-1.5 transition-colors hover:border-term/40 hover:bg-term/[0.04]", children: [_jsx("span", { className: "mono text-[11px] text-term", children: link.to }), _jsx("span", { className: "min-w-0 flex-1 truncate text-[11px] text-ink-3 transition-colors group-hover:text-ink", children: link.label }), _jsx("span", { className: "mono shrink-0 text-ink-4 transition-colors group-hover:text-term", "aria-hidden": true, children: "\u2192" })] }) }, link.to))) }), _jsxs("p", { className: "mono mt-2.5 text-[11px] text-ink-4", children: ["Press ", _jsx("kbd", { className: "rounded-[1px] border border-line-3 bg-raised px-1 text-ink-3", children: "Ctrl" }), "+", _jsx("kbd", { className: "rounded-[1px] border border-line-3 bg-raised px-1 text-ink-3", children: "K" }), " anywhere in the console to jump to a route or run a command."] })] })] }));
}
