"""Phase 2: Add security events, threats, incidents, indicators models and relationships

Revision ID: 52c1b962d103
Revises: 
Create Date: 2026-09-21 10:06:11.714970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c1b962d103'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', 'FALSE_POSITIVE', name='incidentstatus'), nullable=False),
    sa.Column('threat_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('evidence_event_ids', sa.JSON(), nullable=True),
    sa.Column('affected_assets', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=True)
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('indicator_type', sa.Enum('IP', 'DOMAIN', 'URL', 'HASH', 'EMAIL', name='indicatortype'), nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPICIOUS', 'WHITELISTED', 'EXPIRED', 'UNDER_REVIEW', name='indicatorstatus'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('related_events', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('threat_actor', sa.String(), nullable=True),
    sa.Column('campaign', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('whois', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_index(op.f('ix_indicators_indicator_id'), 'indicators', ['indicator_id'], unique=True)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', 'FALSE_POSITIVE', name='eventstatus'), nullable=False),
    sa.Column('detection_rule', sa.String(), nullable=True),
    sa.Column('threat_id', sa.String(), nullable=True),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_event_id'), 'security_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('incident_evidence',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['security_events.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'event_id')
    )
    op.create_table('threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threat_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('threat_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', 'FALSE_POSITIVE', name='eventstatus'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('detection_rule', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mitre', sa.JSON(), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('related_event_ids', sa.JSON(), nullable=True),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.incident_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threats_id'), 'threats', ['id'], unique=False)
    op.create_index(op.f('ix_threats_threat_id'), 'threats', ['threat_id'], unique=True)
    # ### end Alembic commands ###

    # Add additional indexes for SOC workloads
    op.create_index('ix_security_events_timestamp', 'security_events', ['timestamp'])
    op.create_index('ix_security_events_severity', 'security_events', ['severity'])
    op.create_index('ix_security_events_source_ip', 'security_events', ['source'])
    op.create_index('ix_security_events_target_ip', 'security_events', ['target'])
    
    op.create_index('ix_threats_severity', 'threats', ['severity'])
    op.create_index('ix_threats_status', 'threats', ['status'])
    
    op.create_index('ix_incidents_severity', 'incidents', ['severity'])
    op.create_index('ix_incidents_status', 'incidents', ['status'])
    
    op.create_index('ix_indicators_value', 'indicators', ['value'])
    op.create_index('ix_indicators_indicator_type', 'indicators', ['indicator_type'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop additional indexes
    op.drop_index('ix_indicators_indicator_type', table_name='indicators')
    op.drop_index('ix_indicators_value', table_name='indicators')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_severity', table_name='incidents')
    op.drop_index('ix_threats_status', table_name='threats')
    op.drop_index('ix_threats_severity', table_name='threats')
    op.drop_index('ix_security_events_target_ip', table_name='security_events')
    op.drop_index('ix_security_events_source_ip', table_name='security_events')
    op.drop_index('ix_security_events_severity', table_name='security_events')
    op.drop_index('ix_security_events_timestamp', table_name='security_events')
    
    op.drop_index(op.f('ix_threats_threat_id'), table_name='threats')
    op.drop_index(op.f('ix_threats_id'), table_name='threats')
    op.drop_table('threats')
    op.drop_table('incident_evidence')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_indicators_indicator_id'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###