import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { forwardRef } from 'react';
import { ChevronDown } from 'lucide-react';
import { cn } from '@/utils/cn';
export const Select = forwardRef(function Select({ className, label, options, icon, compact, id, ...props }, ref) {
    const selectId = id ?? `sel-${label?.replace(/\s+/g, '-').toLowerCase() ?? 'field'}`;
    return (_jsxs("div", { className: "min-w-0", children: [label ? _jsx("label", { htmlFor: selectId, className: "label-xs mb-1 block", children: label }) : null, _jsxs("div", { className: "relative", children: [icon ? (_jsx("span", { className: "pointer-events-none absolute top-1/2 left-2 -translate-y-1/2 text-ink-4", "aria-hidden": true, children: icon })) : null, _jsx("select", { ref: ref, id: selectId, className: cn('w-full appearance-none rounded-[2px] border border-line-2 bg-base pr-7 text-xs text-ink-2', 'font-mono uppercase tracking-[0.01em] transition-colors hover:border-line-3', 'focus:border-term/60 focus:text-ink focus:outline-none disabled:opacity-50', compact ? 'h-6 pl-2 text-[10.5px]' : 'h-8 pl-2.5', icon && (compact ? 'pl-6' : 'pl-7'), className), ...props, children: options.map((option) => (_jsx("option", { value: option.value, disabled: option.disabled, className: "bg-panel text-ink", children: option.label }, option.value))) }), _jsx(ChevronDown, { className: "pointer-events-none absolute top-1/2 right-2 size-3 -translate-y-1/2 text-ink-4", "aria-hidden": true })] })] }));
});
/** Accessible switch used throughout Settings. */
export function Toggle({ checked, onChange, label, description, disabled }) {
    return (_jsxs("label", { className: cn('flex cursor-pointer items-start justify-between gap-4 rounded-[2px] border border-transparent px-2 py-1.5 transition-colors hover:border-line hover:bg-panel-2', disabled && 'cursor-not-allowed opacity-50'), children: [_jsxs("span", { className: "min-w-0", children: [_jsx("span", { className: "block text-xs font-medium text-ink-2", children: label }), description ? _jsx("span", { className: "mt-0.5 block text-[10.5px] leading-relaxed text-ink-4", children: description }) : null] }), _jsxs("span", { className: "relative mt-0.5 shrink-0", children: [_jsx("input", { type: "checkbox", role: "switch", checked: checked, disabled: disabled, onChange: (e) => onChange(e.target.checked), className: "peer sr-only" }), _jsx("span", { "aria-hidden": true, className: cn('block h-4 w-8 rounded-[2px] border transition-colors duration-200', checked ? 'border-term/50 bg-term/25' : 'border-line-3 bg-raised', 'peer-focus-visible:outline peer-focus-visible:outline-1 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-term') }), _jsx("span", { "aria-hidden": true, className: cn('absolute top-[3px] size-[10px] rounded-[1px] transition-all duration-200', checked ? 'left-[19px] bg-term' : 'left-[3px] bg-ink-4') })] })] }));
}
